'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UvARescue.Usar.Lib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Achilles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Achilles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Apriori() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Apriori", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AprioriComm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AprioriComm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AprioriMobility() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AprioriMobility", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AprioriVictims() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AprioriVictims", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ArrowLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArrowLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ArrowRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArrowRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AutoFit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AutoFit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Button_Answer_to_Life() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_Answer_to_Life", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Camera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Camera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CameraOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CameraOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CameraOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CameraOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Clearspace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clearspace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ConfigDelete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfigDelete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ConfigNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfigNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ConfigOpen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfigOpen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ConfigReload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfigReload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ConfigSave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfigSave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ConfigSaveAs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConfigSaveAs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Drive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Drive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ExtractFrontiers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExtractFrontiers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Flip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FolderSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FolderSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Freespace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Freespace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frontiers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frontiers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FrontLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FrontLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FrontRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FrontRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GeoTiff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GeoTiff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Halt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Halt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JamesBond() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JamesBond", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jupiter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jupiter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lightning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lightning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LightStatus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LightStatus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Matrix() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Matrix", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mobility() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mobility", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Move() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Move", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Network() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Network", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Notes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Notes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Obstacles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Obstacles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OmniMap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OmniMap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Picture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Picture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Power() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Power", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Radar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Radar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ready() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ready", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Reset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Reverse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reverse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rewind() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rewind", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Safespace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Safespace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Seal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Seal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Shoot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shoot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignalAnalog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignalAnalog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignalDigital() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignalDigital", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SpeedDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpeedDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SpeedUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpeedUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property StopDrive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StopDrive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sync() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sync", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TurnLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TurnRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Victims() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Victims", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property View() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("View", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ZoomIn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomIn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ZoomOut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomOut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
