'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool with the command: xsd gpx.xsd /classes /language:vb /namespace:gpx.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization
Imports System.Xml.Schema 'manual added
Imports System.Xml.Schema.XmlSchemaImport

'
'This source code was auto-generated by xsd, Version=2.0.50727.42.
'
Namespace gpx


    ' no effect    System.Xml.Serialization.XmlSchemaProvider("http://www.topografix.com/GPX/1/1/gpx.xsd"),
    '      System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.topografix.com/GPX/1/1"), _
    '      System.Xml.Serialization.XmlAttribute("schemaLocation", [Namespace]:="http://www.w3.org/2001/XMLSchema-instance"), _





    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.topografix.com/GPX/1/1"), _
     System.Xml.Serialization.XmlRootAttribute("gpx", [Namespace]:="http://www.topografix.com/GPX/1/1", IsNullable:=False)> _
    Partial Public Class gpxType

        Private schemaLocationField As String 'manually added

        Private metadataField As metadataType

        Private wptField() As wptType

        Private rteField() As rteType

        Private trkField() As trkType

        Private extensionsField As extensionsType

        Private versionField As String

        Private creatorField As String

        Public Sub New()
            MyBase.New()
            Me.versionField = "1.1" 'version of the GPX-standard

            'Manually added

            Me.schemaLocationField = "http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd"


            Me.creatorField = My.Application.Info.Title

            'Me.metadataField = New metadataType()

            'Me.metadataField.copyright.year = "2006-2008"
            'Me.metadataField.copyright.license = My.Application.Info.Copyright
            'Me.metadataField.copyright.author = My.Application.Info.CompanyName


        End Sub


        '''Manually added<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute([Namespace]:="http://www.w3.org/2001/XMLSchema-instance")> _
        Public Property schemaLocation() As String
            Get
                Return Me.schemaLocationField
            End Get
            Set(ByVal value As String)
                Me.schemaLocationField = value
            End Set
        End Property

        '''<remarks/>
        Public Property metadata() As metadataType
            Get
                Return Me.metadataField
            End Get
            Set(ByVal value As metadataType)
                Me.metadataField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("wpt")> _
        Public Property wpt() As wptType()
            Get
                Return Me.wptField
            End Get
            Set(ByVal value As wptType())
                Me.wptField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("rte")> _
        Public Property rte() As rteType()
            Get
                Return Me.rteField
            End Get
            Set(ByVal value As rteType())
                Me.rteField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("trk")> _
        Public Property trk() As trkType()
            Get
                Return Me.trkField
            End Get
            Set(ByVal value As trkType())
                Me.trkField = value
            End Set
        End Property

        '''<remarks/>
        Public Property extensions() As extensionsType
            Get
                Return Me.extensionsField
            End Get
            Set(ByVal value As extensionsType)
                Me.extensionsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set(ByVal value As String)
                Me.versionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property creator() As String
            Get
                Return Me.creatorField
            End Get
            Set(ByVal value As String)
                Me.creatorField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.topografix.com/GPX/1/1")> _
    Partial Public Class metadataType

        Private nameField As String

        Private descField As String

        Private authorField As personType

        Private copyrightField As copyrightType

        Private linkField() As linkType

        Private timeField As Date

        Private timeFieldSpecified As Boolean

        Private keywordsField As String

        Private boundsField As boundsType

        Private extensionsField As extensionsType

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(ByVal value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property desc() As String
            Get
                Return Me.descField
            End Get
            Set(ByVal value As String)
                Me.descField = value
            End Set
        End Property

        '''<remarks/>
        Public Property author() As personType
            Get
                Return Me.authorField
            End Get
            Set(ByVal value As personType)
                Me.authorField = value
            End Set
        End Property

        '''<remarks/>
        Public Property copyright() As copyrightType
            Get
                Return Me.copyrightField
            End Get
            Set(ByVal value As copyrightType)
                Me.copyrightField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("link")> _
        Public Property link() As linkType()
            Get
                Return Me.linkField
            End Get
            Set(ByVal value As linkType())
                Me.linkField = value
            End Set
        End Property

        '''<remarks/>
        Public Property time() As Date
            Get
                Return Me.timeField
            End Get
            Set(ByVal value As Date)
                Me.timeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property timeSpecified() As Boolean
            Get
                Return Me.timeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.timeFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property keywords() As String
            Get
                Return Me.keywordsField
            End Get
            Set(ByVal value As String)
                Me.keywordsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property bounds() As boundsType
            Get
                Return Me.boundsField
            End Get
            Set(ByVal value As boundsType)
                Me.boundsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property extensions() As extensionsType
            Get
                Return Me.extensionsField
            End Get
            Set(ByVal value As extensionsType)
                Me.extensionsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.topografix.com/GPX/1/1")> _
    Partial Public Class personType

        Private nameField As String

        Private emailField As emailType

        Private linkField As linkType

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(ByVal value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property email() As emailType
            Get
                Return Me.emailField
            End Get
            Set(ByVal value As emailType)
                Me.emailField = value
            End Set
        End Property

        '''<remarks/>
        Public Property link() As linkType
            Get
                Return Me.linkField
            End Get
            Set(ByVal value As linkType)
                Me.linkField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.topografix.com/GPX/1/1")> _
    Partial Public Class emailType

        Private idField As String

        Private domainField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property domain() As String
            Get
                Return Me.domainField
            End Get
            Set(ByVal value As String)
                Me.domainField = value
            End Set
        End Property

        Protected Overrides Sub Finalize()
            MyBase.Finalize()
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.topografix.com/GPX/1/1")> _
    Partial Public Class trksegType

        Private trkptField() As wptType

        Private extensionsField As extensionsType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("trkpt")> _
        Public Property trkpt() As wptType()
            Get
                Return Me.trkptField
            End Get
            Set(ByVal value As wptType())
                Me.trkptField = value
            End Set
        End Property

        '''<remarks/>
        Public Property extensions() As extensionsType
            Get
                Return Me.extensionsField
            End Get
            Set(ByVal value As extensionsType)
                Me.extensionsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.topografix.com/GPX/1/1")> _
    Partial Public Class wptType

        Private eleField As Decimal

        Private eleFieldSpecified As Boolean

        Private timeField As Date

        Private timeFieldSpecified As Boolean

        Private magvarField As Decimal

        Private magvarFieldSpecified As Boolean

        Private geoidheightField As Decimal

        Private geoidheightFieldSpecified As Boolean

        Private nameField As String

        Private cmtField As String

        Private descField As String

        Private srcField As String

        Private linkField() As linkType

        Private symField As String

        Private typeField As String

        Private fixField As fixType

        Private fixFieldSpecified As Boolean

        Private satField As String

        Private hdopField As Decimal

        Private hdopFieldSpecified As Boolean

        Private vdopField As Decimal

        Private vdopFieldSpecified As Boolean

        Private pdopField As Decimal

        Private pdopFieldSpecified As Boolean

        Private ageofdgpsdataField As Decimal

        Private ageofdgpsdataFieldSpecified As Boolean

        Private dgpsidField As String

        Private extensionsField As extensionsType

        Private latField As Decimal

        Private lonField As Decimal

        '''<remarks/>
        Public Property ele() As Decimal
            Get
                Return Me.eleField
            End Get
            Set(ByVal value As Decimal)
                Me.eleField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property eleSpecified() As Boolean
            Get
                Return Me.eleFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.eleFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property time() As Date
            Get
                Return Me.timeField
            End Get
            Set(ByVal value As Date)
                Me.timeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property timeSpecified() As Boolean
            Get
                Return Me.timeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.timeFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property magvar() As Decimal
            Get
                Return Me.magvarField
            End Get
            Set(ByVal value As Decimal)
                Me.magvarField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property magvarSpecified() As Boolean
            Get
                Return Me.magvarFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.magvarFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property geoidheight() As Decimal
            Get
                Return Me.geoidheightField
            End Get
            Set(ByVal value As Decimal)
                Me.geoidheightField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property geoidheightSpecified() As Boolean
            Get
                Return Me.geoidheightFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.geoidheightFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(ByVal value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property cmt() As String
            Get
                Return Me.cmtField
            End Get
            Set(ByVal value As String)
                Me.cmtField = value
            End Set
        End Property

        '''<remarks/>
        Public Property desc() As String
            Get
                Return Me.descField
            End Get
            Set(ByVal value As String)
                Me.descField = value
            End Set
        End Property

        '''<remarks/>
        Public Property src() As String
            Get
                Return Me.srcField
            End Get
            Set(ByVal value As String)
                Me.srcField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("link")> _
        Public Property link() As linkType()
            Get
                Return Me.linkField
            End Get
            Set(ByVal value As linkType())
                Me.linkField = value
            End Set
        End Property

        '''<remarks/>
        Public Property sym() As String
            Get
                Return Me.symField
            End Get
            Set(ByVal value As String)
                Me.symField = value
            End Set
        End Property

        '''<remarks/>
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set(ByVal value As String)
                Me.typeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property fix() As fixType
            Get
                Return Me.fixField
            End Get
            Set(ByVal value As fixType)
                Me.fixField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property fixSpecified() As Boolean
            Get
                Return Me.fixFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.fixFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")> _
        Public Property sat() As String
            Get
                Return Me.satField
            End Get
            Set(ByVal value As String)
                Me.satField = value
            End Set
        End Property

        '''<remarks/>
        Public Property hdop() As Decimal
            Get
                Return Me.hdopField
            End Get
            Set(ByVal value As Decimal)
                Me.hdopField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property hdopSpecified() As Boolean
            Get
                Return Me.hdopFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.hdopFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property vdop() As Decimal
            Get
                Return Me.vdopField
            End Get
            Set(ByVal value As Decimal)
                Me.vdopField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property vdopSpecified() As Boolean
            Get
                Return Me.vdopFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.vdopFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property pdop() As Decimal
            Get
                Return Me.pdopField
            End Get
            Set(ByVal value As Decimal)
                Me.pdopField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property pdopSpecified() As Boolean
            Get
                Return Me.pdopFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.pdopFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property ageofdgpsdata() As Decimal
            Get
                Return Me.ageofdgpsdataField
            End Get
            Set(ByVal value As Decimal)
                Me.ageofdgpsdataField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ageofdgpsdataSpecified() As Boolean
            Get
                Return Me.ageofdgpsdataFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.ageofdgpsdataFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> _
        Public Property dgpsid() As String
            Get
                Return Me.dgpsidField
            End Get
            Set(ByVal value As String)
                Me.dgpsidField = value
            End Set
        End Property

        '''<remarks/>
        Public Property extensions() As extensionsType
            Get
                Return Me.extensionsField
            End Get
            Set(ByVal value As extensionsType)
                Me.extensionsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property lat() As Decimal
            Get
                Return Me.latField
            End Get
            Set(ByVal value As Decimal)
                Me.latField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property lon() As Decimal
            Get
                Return Me.lonField
            End Get
            Set(ByVal value As Decimal)
                Me.lonField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.topografix.com/GPX/1/1")> _
    Partial Public Class linkType

        Private textField As String

        Private typeField As String

        Private hrefField As String

        '''<remarks/>
        Public Property text() As String
            Get
                Return Me.textField
            End Get
            Set(ByVal value As String)
                Me.textField = value
            End Set
        End Property

        '''<remarks/>
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set(ByVal value As String)
                Me.typeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property href() As String
            Get
                Return Me.hrefField
            End Get
            Set(ByVal value As String)
                Me.hrefField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.topografix.com/GPX/1/1")> _
    Public Enum fixType

        '''<remarks/>
        none

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2d")> _
        Item2d

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("3d")> _
        Item3d

        '''<remarks/>
        dgps

        '''<remarks/>
        pps
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.topografix.com/GPX/1/1")> _
    Partial Public Class extensionsType

        Private anyField() As System.Xml.XmlElement

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set(ByVal value As System.Xml.XmlElement())
                Me.anyField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.topografix.com/GPX/1/1")> _
    Partial Public Class trkType

        Private nameField As String

        Private cmtField As String

        Private descField As String

        Private srcField As String

        Private linkField() As linkType

        Private numberField As String

        Private typeField As String

        Private extensionsField As extensionsType

        Private trksegField() As trksegType

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(ByVal value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property cmt() As String
            Get
                Return Me.cmtField
            End Get
            Set(ByVal value As String)
                Me.cmtField = value
            End Set
        End Property

        '''<remarks/>
        Public Property desc() As String
            Get
                Return Me.descField
            End Get
            Set(ByVal value As String)
                Me.descField = value
            End Set
        End Property

        '''<remarks/>
        Public Property src() As String
            Get
                Return Me.srcField
            End Get
            Set(ByVal value As String)
                Me.srcField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("link")> _
        Public Property link() As linkType()
            Get
                Return Me.linkField
            End Get
            Set(ByVal value As linkType())
                Me.linkField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")> _
        Public Property number() As String
            Get
                Return Me.numberField
            End Get
            Set(ByVal value As String)
                Me.numberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set(ByVal value As String)
                Me.typeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property extensions() As extensionsType
            Get
                Return Me.extensionsField
            End Get
            Set(ByVal value As extensionsType)
                Me.extensionsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("trkseg")> _
        Public Property trkseg() As trksegType()
            Get
                Return Me.trksegField
            End Get
            Set(ByVal value As trksegType())
                Me.trksegField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.topografix.com/GPX/1/1")> _
    Partial Public Class rteType

        Private nameField As String

        Private cmtField As String

        Private descField As String

        Private srcField As String

        Private linkField() As linkType

        Private numberField As String

        Private typeField As String

        Private extensionsField As extensionsType

        Private rteptField() As wptType

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(ByVal value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property cmt() As String
            Get
                Return Me.cmtField
            End Get
            Set(ByVal value As String)
                Me.cmtField = value
            End Set
        End Property

        '''<remarks/>
        Public Property desc() As String
            Get
                Return Me.descField
            End Get
            Set(ByVal value As String)
                Me.descField = value
            End Set
        End Property

        '''<remarks/>
        Public Property src() As String
            Get
                Return Me.srcField
            End Get
            Set(ByVal value As String)
                Me.srcField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("link")> _
        Public Property link() As linkType()
            Get
                Return Me.linkField
            End Get
            Set(ByVal value As linkType())
                Me.linkField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")> _
        Public Property number() As String
            Get
                Return Me.numberField
            End Get
            Set(ByVal value As String)
                Me.numberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set(ByVal value As String)
                Me.typeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property extensions() As extensionsType
            Get
                Return Me.extensionsField
            End Get
            Set(ByVal value As extensionsType)
                Me.extensionsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("rtept")> _
        Public Property rtept() As wptType()
            Get
                Return Me.rteptField
            End Get
            Set(ByVal value As wptType())
                Me.rteptField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.topografix.com/GPX/1/1")> _
    Partial Public Class boundsType

        Private minlatField As Decimal

        Private minlonField As Decimal

        Private maxlatField As Decimal

        Private maxlonField As Decimal

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property minlat() As Decimal
            Get
                Return Me.minlatField
            End Get
            Set(ByVal value As Decimal)
                Me.minlatField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property minlon() As Decimal
            Get
                Return Me.minlonField
            End Get
            Set(ByVal value As Decimal)
                Me.minlonField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property maxlat() As Decimal
            Get
                Return Me.maxlatField
            End Get
            Set(ByVal value As Decimal)
                Me.maxlatField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property maxlon() As Decimal
            Get
                Return Me.maxlonField
            End Get
            Set(ByVal value As Decimal)
                Me.maxlonField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.topografix.com/GPX/1/1")> _
    Partial Public Class copyrightType

        Private yearField As String

        Private licenseField As String

        Private authorField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="gYear")> _
        Public Property year() As String
            Get
                Return Me.yearField
            End Get
            Set(ByVal value As String)
                Me.yearField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI")> _
        Public Property license() As String
            Get
                Return Me.licenseField
            End Get
            Set(ByVal value As String)
                Me.licenseField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property author() As String
            Get
                Return Me.authorField
            End Get
            Set(ByVal value As String)
                Me.authorField = value
            End Set
        End Property
    End Class
End Namespace
