#!/bin/bash

#$(for i in $(find ../Config -not -path '*/.svn/*' -and -not -path '*/.svn' -type d -print); do svn --username anonymous log $i > $i/revisions2006.txt; done)
#$(for i in $(find ../Make -not -path '*/.svn/*' -and -not -path '*/.svn' -type d -print); do svn --username anonymous log $i > $i/revisions2006.txt; done)
#$(for i in $(find ../Src -not -path '*/.svn/*' -and -not -path '*/.svn' -type d -print); do svn --username anonymous log $i > $i/revisions2006.txt; done)

#$(for i in $(find ../Agent -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r252:671 $i > $i/revisions2007.txt; done)
#$(for i in $(find ../Communication -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r252:671 $i > $i/revisions2007.txt; done)
#$(for i in $(find ../ImageAnalysis -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r252:671 $i > $i/revisions2007.txt; done)
#$(for i in $(find ../Math -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r252:671 $i > $i/revisions2007.txt; done)
#$(for i in $(find ../Slam -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r252:671 $i > $i/revisions2007.txt; done)
#$(for i in $(find ../Usar -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r252:671 $i > $i/revisions2007.txt; done)

#$(for i in $(find ../Agent -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r672:1349 $i > $i/revisions2008.txt; done)
#$(for i in $(find ../Communication -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r672:1349 $i > $i/revisions2008.txt; done)
#$(for i in $(find ../ImageAnalysis -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r672:1349 $i > $i/revisions2008.txt; done)
#$(for i in $(find ../Math -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r672:1349 $i > $i/revisions2008.txt; done)
#$(for i in $(find ../Slam -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r672:1349 $i > $i/revisions2008.txt; done)
#$(for i in $(find ../Usar -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r672:1349 $i > $i/revisions2008.txt; done)

#$(for i in $(find ../Agent -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r1350:1913 $i > $i/revisions2009.txt; done)
#$(for i in $(find ../Communication -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r1350:1913 $i > $i/revisions2009.txt; done)
#$(for i in $(find ../ImageAnalysis -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r1350:1913 $i > $i/revisions2009.txt; done)
#$(for i in $(find ../Math -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r1350:1913 $i > $i/revisions2009.txt; done)
#$(for i in $(find ../Slam -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r1350:1913 $i > $i/revisions2009.txt; done)
#$(for i in $(find ../Usar -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r1350:1913 $i > $i/revisions2009.txt; done)
#$(for i in $(find ../Tools -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r1350:1913 $i > $i/revisions2009.txt; done)

#$(for i in $(find ../Agent -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r1914:2163  $i > $i/revisions2010.txt; done)
#$(for i in $(find ../Communication -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r1914:2163  $i > $i/revisions2010.txt; done)
#$(for i in $(find ../ImageAnalysis -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r1914:2163  $i > $i/revisions2010.txt; done)
#$(for i in $(find ../Math -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r1914:2163  $i > $i/revisions2010.txt; done)
#$(for i in $(find ../Slam -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r1914:2163  $i > $i/revisions2010.txt; done)
#$(for i in $(find ../Usar -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r1914:2163  $i > $i/revisions2010.txt; done)
#$(for i in $(find ../Tools -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r1914:2163  $i > $i/revisions2010.txt; done)

$(for i in $(find .. -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r2164:2228  $i > $i/revisions2011.txt; done)
$(for i in $(find ../Agent -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r2164:2228  $i > $i/revisions2011.txt; done)
$(for i in $(find ../Communication -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r2164:2228  $i > $i/revisions2011.txt; done)
$(for i in $(find ../ImageAnalysis -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r2164:2228  $i > $i/revisions2011.txt; done)
$(for i in $(find ../Math -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r2164:2228  $i > $i/revisions2011.txt; done)
$(for i in $(find ../Slam -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r2164:2228  $i > $i/revisions2011.txt; done)
$(for i in $(find ../Usar -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r2164:2228  $i > $i/revisions2011.txt; done)
$(for i in $(find ../Tools -not -path '*/.svn/*' -and -not -path '*/.svn' -and -not -path '*/bin/*' -and -not -path '*/obj/*' -type d -print); do svn log -r2164:2228  $i > $i/revisions2011.txt; done)